In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as stats
import itertools

In [3]:
binary_csv = pd.read_csv("../results/big_picture_0/binary0.json_results.csv")
binary_csv

                           Unnamed: 0    0         1             2           3
0      (1, 300, np.float64(0.1), 120)  0.0  0.527083  5.834585e+07  57245002.0
1      (1, 300, np.float64(0.1), 130)  0.0  0.618750  6.712347e+07  66000430.0
2      (1, 300, np.float64(0.1), 140)  0.0  0.685417  6.120505e+07  59728671.5
3      (1, 300, np.float64(0.1), 150)  0.0  0.731250  5.060486e+07  48218037.0
4      (1, 300, np.float64(0.1), 160)  0.0  0.775000  3.892686e+07  38053143.0
...                               ...  ...       ...           ...         ...
5935  (11, 400, np.float64(0.9), 170)  0.0  0.114583  8.532167e+07  85205030.5
5936  (11, 400, np.float64(0.9), 180)  0.0  0.070833  8.547898e+07  85483014.5
5937  (11, 400, np.float64(0.9), 190)  0.0  0.018750  8.435803e+07  83978479.0
5938  (11, 400, np.float64(0.9), 200)  0.0  0.002083  8.275957e+07  82775313.0
5939  (11, 400, np.float64(0.9), 210)  0.0  0.002083  8.273027e+07  82874498.0

[5940 rows x 5 columns]

In [4]:
otsu_csv = pd.read_csv("../results/big_picture_0/otsu0.json_results.csv")
otsu_csv

                    Unnamed: 0  0         1             2            3
0    (9, 400, np.float64(0.8))  3  0.356250  1.140173e+08  113759764.5
1    (7, 390, np.float64(0.8))  3  0.354167  1.097493e+08  109367726.5
2    (7, 400, np.float64(0.8))  3  0.354167  1.096464e+08  109472264.0
3    (9, 380, np.float64(0.8))  3  0.354167  1.151023e+08  114712632.5
4    (9, 390, np.float64(0.8))  3  0.354167  1.148804e+08  114558101.0
..                         ... ..       ...           ...          ...
589  (1, 360, np.float64(0.9))  3  0.004167  3.837576e+07   37557865.0
590  (1, 370, np.float64(0.9))  3  0.004167  3.816661e+07   37634977.0
591  (1, 380, np.float64(0.9))  3  0.004167  3.913666e+07   38679857.0
592  (1, 390, np.float64(0.9))  3  0.004167  3.969441e+07   39626169.5
593  (1, 400, np.float64(0.9))  3  0.004167  3.927863e+07   38871923.5

[594 rows x 5 columns]

In [8]:
otsu_csv.sort_values("1", ascending= False)

                    Unnamed: 0  0         1             2            3
0    (9, 400, np.float64(0.8))  3  0.356250  1.140173e+08  113759764.5
3    (9, 380, np.float64(0.8))  3  0.354167  1.151023e+08  114712632.5
4    (9, 390, np.float64(0.8))  3  0.354167  1.148804e+08  114558101.0
1    (7, 390, np.float64(0.8))  3  0.354167  1.097493e+08  109367726.5
2    (7, 400, np.float64(0.8))  3  0.354167  1.096464e+08  109472264.0
..                         ... ..       ...           ...          ...
589  (1, 360, np.float64(0.9))  3  0.004167  3.837576e+07   37557865.0
590  (1, 370, np.float64(0.9))  3  0.004167  3.816661e+07   37634977.0
591  (1, 380, np.float64(0.9))  3  0.004167  3.913666e+07   38679857.0
592  (1, 390, np.float64(0.9))  3  0.004167  3.969441e+07   39626169.5
593  (1, 400, np.float64(0.9))  3  0.004167  3.927863e+07   38871923.5

[594 rows x 5 columns]

In [9]:
binary_csv.sort_values("1", ascending= False)

                         Unnamed: 0    0         1             2           3
885  (1, 390, np.float64(0.8), 170)  0.0  0.883333  3.291389e+07  31922490.5
975  (1, 400, np.float64(0.8), 170)  0.0  0.883333  3.279215e+07  31989650.5
795  (1, 380, np.float64(0.8), 170)  0.0  0.879167  3.275046e+07  31652262.5
705  (1, 370, np.float64(0.8), 170)  0.0  0.875000  3.334838e+07  32128232.5
525  (1, 350, np.float64(0.8), 170)  0.0  0.872917  3.316063e+07  32383020.0
..                              ...  ...       ...           ...         ...
447  (1, 340, np.float64(0.9), 190)  0.0  0.000000  2.838531e+07  26343820.5
357  (1, 330, np.float64(0.9), 190)  0.0  0.000000  2.626784e+07  24173206.5
269  (1, 320, np.float64(0.9), 210)  0.0  0.000000  1.756510e+07  15866479.5
267  (1, 320, np.float64(0.9), 190)  0.0  0.000000  2.765706e+07  25177520.0
359  (1, 330, np.float64(0.9), 210)  0.0  0.000000  1.889853e+07  17473790.0

[5940 rows x 5 columns]