In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as stats
import itertools

In [3]:
binary_csv = pd.read_csv("../results/big_picture_1/binary0.json_results.csv")
binary_csv

                           Unnamed: 0    0         1             2           3
0      (1, 300, np.float64(0.1), 120)  0.0  0.527083  5.979566e+07  59882225.0
1      (1, 300, np.float64(0.1), 130)  0.0  0.618750  6.754187e+07  65960911.0
2      (1, 300, np.float64(0.1), 140)  0.0  0.685417  6.374043e+07  61844184.5
3      (1, 300, np.float64(0.1), 150)  0.0  0.731250  5.369741e+07  52020212.0
4      (1, 300, np.float64(0.1), 160)  0.0  0.775000  4.122299e+07  40144980.5
...                               ...  ...       ...           ...         ...
5935  (11, 400, np.float64(0.9), 170)  0.0  0.114583  8.597592e+07  85749300.0
5936  (11, 400, np.float64(0.9), 180)  0.0  0.070833  8.582991e+07  85755765.0
5937  (11, 400, np.float64(0.9), 190)  0.0  0.018750  8.398316e+07  83825908.0
5938  (11, 400, np.float64(0.9), 200)  0.0  0.002083  8.393722e+07  84027440.5
5939  (11, 400, np.float64(0.9), 210)  0.0  0.002083  8.252909e+07  82836067.5

[5940 rows x 5 columns]

In [5]:
otsu_csv = pd.read_csv("../results/big_picture_1/otsu1.jston_results.csv")
otsu_csv

                    Unnamed: 0  0         1             2            3
0    (7, 390, np.float64(0.8))  3  0.231250  1.079334e+08  107443785.5
1    (7, 400, np.float64(0.8))  3  0.231250  1.092083e+08  108745290.5
2    (9, 370, np.float64(0.8))  3  0.231250  1.135598e+08  113047865.0
3    (9, 380, np.float64(0.8))  3  0.231250  1.135563e+08  112824640.0
4    (9, 390, np.float64(0.8))  3  0.231250  1.135887e+08  113390928.0
..                         ... ..       ...           ...          ...
589  (1, 360, np.float64(0.9))  3  0.002083  3.719454e+07   37753224.0
590  (1, 370, np.float64(0.9))  3  0.002083  3.723033e+07   38084374.5
591  (1, 380, np.float64(0.9))  3  0.002083  3.714411e+07   37478307.5
592  (1, 390, np.float64(0.9))  3  0.002083  3.844482e+07   39169967.5
593  (1, 400, np.float64(0.9))  3  0.002083  3.836222e+07   38776246.0

[594 rows x 5 columns]

In [6]:
otsu_csv.sort_values("1", ascending= False)

                    Unnamed: 0  0         1             2            3
0    (7, 390, np.float64(0.8))  3  0.231250  1.079334e+08  107443785.5
4    (9, 390, np.float64(0.8))  3  0.231250  1.135887e+08  113390928.0
5    (9, 400, np.float64(0.8))  3  0.231250  1.146633e+08  114630436.5
1    (7, 400, np.float64(0.8))  3  0.231250  1.092083e+08  108745290.5
3    (9, 380, np.float64(0.8))  3  0.231250  1.135563e+08  112824640.0
..                         ... ..       ...           ...          ...
589  (1, 360, np.float64(0.9))  3  0.002083  3.719454e+07   37753224.0
590  (1, 370, np.float64(0.9))  3  0.002083  3.723033e+07   38084374.5
591  (1, 380, np.float64(0.9))  3  0.002083  3.714411e+07   37478307.5
592  (1, 390, np.float64(0.9))  3  0.002083  3.844482e+07   39169967.5
593  (1, 400, np.float64(0.9))  3  0.002083  3.836222e+07   38776246.0

[594 rows x 5 columns]

In [7]:
binary_csv.sort_values("1", ascending= False)

                         Unnamed: 0    0         1             2           3
885  (1, 390, np.float64(0.8), 170)  0.0  0.883333  3.269485e+07  31731059.0
975  (1, 400, np.float64(0.8), 170)  0.0  0.883333  3.232669e+07  31571740.5
795  (1, 380, np.float64(0.8), 170)  0.0  0.879167  3.313998e+07  32217314.0
705  (1, 370, np.float64(0.8), 170)  0.0  0.875000  3.400093e+07  32915503.5
525  (1, 350, np.float64(0.8), 170)  0.0  0.872917  3.349821e+07  32511010.0
..                              ...  ...       ...           ...         ...
447  (1, 340, np.float64(0.9), 190)  0.0  0.000000  2.856950e+07  26312730.0
357  (1, 330, np.float64(0.9), 190)  0.0  0.000000  2.820512e+07  25828583.5
269  (1, 320, np.float64(0.9), 210)  0.0  0.000000  1.699308e+07  15199805.0
267  (1, 320, np.float64(0.9), 190)  0.0  0.000000  2.731617e+07  25016809.0
359  (1, 330, np.float64(0.9), 210)  0.0  0.000000  1.690373e+07  14957795.5

[5940 rows x 5 columns]