### Notebook to look at Binary and OTSU - Updated results
The OTSU method has been updated from the original histopathology code to correct for its colour correlation problems

In [1]:
## Imports cell

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as stats
import puck.experiments.best_thresholding.binary_otsu_updated as bou

output_file_dict is a dictionary that returns the paths where the outputs of running bou.main() are saved


adjustment_on adds in the prefix determined by adjustment, which is default, "../",


cli_printout prints out some metadata to the command line interface, because you're using the notebook to access this, I recommend turnning it off.


Typical dictionary keys are "bigpicture0", "bigpicture1", "results0", results1", "output timing", where
-  bigpicture# values are the aggregated results of all the possible pipelines using binary or otsu methods in a .csv, indicated by the # 0 for binary, and 1 for otsu.
- results# values are the folder paths where each parameter search is saved as a csv, similarly indicated by the # 0 for binary, and 1 for otsu.
- output timing's value is a .txt file that tells you the time it took to run all of this



A progress bar will show up beneath the cell that is running this, you can use this to approximate how long the cell will take to run. The more hyperparameters tested, the more time it will likely take.

In [ ]:
output_file_dict = bou.main(
    adjustment_on = True,
    cli_printout = False
    )

100%|██████████| 60/60 [00:18<00:00,  3.23it/s]
  5%|▍         | 2/44 [00:04<01:25,  2.03s/it]

In [2]:
# Check that the dictionary returns sensible paths, if something is off, you might want to check the arguments passed to bou.main()
output_file_dict

NameError: name 'output_file_dict' is not defined

In [ ]:
## Look at the OTSU results for all the hyperparameter tests, 
# column 0 is the parameter combination, 
# column 1 is the method 1 for otsu and 0 for binary, 
# column 2 is the accuracy
# column 3 is the time it took to run this?
# column 4 is the time it took to run this?

otsu_csv = pd.read_csv(output_file_dict.get("bigpicture1"))
otsu_csv

                   Unnamed: 0    0         1             2           3
0    (1, 20, np.float64(0.1))  1.0  0.006250  8.240381e+07  82393271.0
1    (1, 20, np.float64(0.2))  1.0  0.006250  8.127278e+07  84024958.5
2    (1, 30, np.float64(0.1))  1.0  0.012500  8.104327e+07  80234062.5
3    (1, 30, np.float64(0.2))  1.0  0.012500  8.078720e+07  80918583.0
4    (1, 40, np.float64(0.1))  1.0  0.022917  8.038999e+07  81099354.5
5    (1, 40, np.float64(0.2))  1.0  0.022917  7.941319e+07  78406083.0
6    (1, 50, np.float64(0.1))  1.0  0.033333  8.013003e+07  82985479.0
7    (1, 50, np.float64(0.2))  1.0  0.033333  7.933095e+07  80102083.5
8    (1, 60, np.float64(0.1))  1.0  0.035417  8.010334e+07  79923166.5
9    (1, 60, np.float64(0.2))  1.0  0.035417  7.908093e+07  79783645.5
10   (1, 70, np.float64(0.1))  1.0  0.035417  8.038716e+07  78598583.5
11   (1, 70, np.float64(0.2))  1.0  0.035417  7.950410e+07  79629667.0
12   (1, 80, np.float64(0.1))  1.0  0.035417  8.003082e+07  80732916.5
13   (1, 80, np.float64(0.2))  1.0  0.035417  7.916074e+07  78581354.0
14   (1, 90, np.float64(0.1))  1.0  0.039583  7.973900e+07  81427562.5
15   (1, 90, np.float64(0.2))  1.0  0.039583  7.910482e+07  78618000.0
16  (1, 100, np.float64(0.1))  1.0  0.039583  7.928394e+07  80577541.5
17  (1, 100, np.float64(0.2))  1.0  0.039583  7.865989e+07  80071333.0
18  (1, 110, np.float64(0.1))  1.0  0.039583  7.976512e+07  80185750.0
19  (1, 110, np.float64(0.2))  1.0  0.039583  7.872575e+07  79745395.5
20  (1, 120, np.float64(0.1))  1.0  0.039583  8.187928e+07  79807541.5
21  (1, 120, np.float64(0.2))  1.0  0.039583  8.068713e+07  80349334.0
22   (3, 20, np.float64(0.1))  1.0  0.002083  7.773973e+07  77878667.0
23   (3, 20, np.float64(0.2))  1.0  0.002083  7.750082e+07  76422229.0
24   (3, 30, np.float64(0.1))  1.0  0.008333  7.640493e+07  76730708.5
25   (3, 30, np.float64(0.2))  1.0  0.008333  7.597180e+07  76377812.5
26   (3, 40, np.float64(0.1))  1.0  0.012500  7.660838e+07  76845125.5
27   (3, 40, np.float64(0.2))  1.0  0.012500  7.529038e+07  75156396.0
28   (3, 50, np.float64(0.1))  1.0  0.020833  7.550767e+07  76077979.0
29   (3, 50, np.float64(0.2))  1.0  0.020833  7.514781e+07  74897500.0
30   (3, 60, np.float64(0.1))  1.0  0.022917  7.632848e+07  75912792.0
31   (3, 60, np.float64(0.2))  1.0  0.022917  7.545163e+07  74132854.5
32   (3, 70, np.float64(0.1))  1.0  0.027083  7.600617e+07  77248729.0
33   (3, 70, np.float64(0.2))  1.0  0.027083  7.583812e+07  74275458.0
34   (3, 80, np.float64(0.1))  1.0  0.033333  7.654319e+07  76973479.0
35   (3, 80, np.float64(0.2))  1.0  0.033333  7.479984e+07  73833000.0
36   (3, 90, np.float64(0.1))  1.0  0.033333  7.616238e+07  73370146.5
37   (3, 90, np.float64(0.2))  1.0  0.033333  7.501010e+07  74445125.0
38  (3, 100, np.float64(0.1))  1.0  0.033333  7.497068e+07  72823521.0
39  (3, 100, np.float64(0.2))  1.0  0.033333  7.465825e+07  73983000.0
40  (3, 110, np.float64(0.1))  1.0  0.035417  5.867008e+07  56802125.5
41  (3, 110, np.float64(0.2))  1.0  0.035417  5.770868e+07  56520166.5
42  (3, 120, np.float64(0.1))  1.0  0.035417  5.745355e+07  55786958.0
43  (3, 120, np.float64(0.2))  1.0  0.035417  5.810667e+07  57340750.5

In [ ]:
# Sort by the highest accuracy
otsu_csv.sort_values("1", ascending= False)

                   Unnamed: 0    0         1             2           3
20  (1, 120, np.float64(0.1))  1.0  0.039583  8.187928e+07  79807541.5
21  (1, 120, np.float64(0.2))  1.0  0.039583  8.068713e+07  80349334.0
19  (1, 110, np.float64(0.2))  1.0  0.039583  7.872575e+07  79745395.5
18  (1, 110, np.float64(0.1))  1.0  0.039583  7.976512e+07  80185750.0
17  (1, 100, np.float64(0.2))  1.0  0.039583  7.865989e+07  80071333.0
16  (1, 100, np.float64(0.1))  1.0  0.039583  7.928394e+07  80577541.5
15   (1, 90, np.float64(0.2))  1.0  0.039583  7.910482e+07  78618000.0
14   (1, 90, np.float64(0.1))  1.0  0.039583  7.973900e+07  81427562.5
13   (1, 80, np.float64(0.2))  1.0  0.035417  7.916074e+07  78581354.0
41  (3, 110, np.float64(0.2))  1.0  0.035417  5.770868e+07  56520166.5
42  (3, 120, np.float64(0.1))  1.0  0.035417  5.745355e+07  55786958.0
40  (3, 110, np.float64(0.1))  1.0  0.035417  5.867008e+07  56802125.5
43  (3, 120, np.float64(0.2))  1.0  0.035417  5.810667e+07  57340750.5
12   (1, 80, np.float64(0.1))  1.0  0.035417  8.003082e+07  80732916.5
11   (1, 70, np.float64(0.2))  1.0  0.035417  7.950410e+07  79629667.0
10   (1, 70, np.float64(0.1))  1.0  0.035417  8.038716e+07  78598583.5
9    (1, 60, np.float64(0.2))  1.0  0.035417  7.908093e+07  79783645.5
8    (1, 60, np.float64(0.1))  1.0  0.035417  8.010334e+07  79923166.5
38  (3, 100, np.float64(0.1))  1.0  0.033333  7.497068e+07  72823521.0
37   (3, 90, np.float64(0.2))  1.0  0.033333  7.501010e+07  74445125.0
36   (3, 90, np.float64(0.1))  1.0  0.033333  7.616238e+07  73370146.5
35   (3, 80, np.float64(0.2))  1.0  0.033333  7.479984e+07  73833000.0
34   (3, 80, np.float64(0.1))  1.0  0.033333  7.654319e+07  76973479.0
39  (3, 100, np.float64(0.2))  1.0  0.033333  7.465825e+07  73983000.0
6    (1, 50, np.float64(0.1))  1.0  0.033333  8.013003e+07  82985479.0
7    (1, 50, np.float64(0.2))  1.0  0.033333  7.933095e+07  80102083.5
32   (3, 70, np.float64(0.1))  1.0  0.027083  7.600617e+07  77248729.0
33   (3, 70, np.float64(0.2))  1.0  0.027083  7.583812e+07  74275458.0
30   (3, 60, np.float64(0.1))  1.0  0.022917  7.632848e+07  75912792.0
31   (3, 60, np.float64(0.2))  1.0  0.022917  7.545163e+07  74132854.5
4    (1, 40, np.float64(0.1))  1.0  0.022917  8.038999e+07  81099354.5
5    (1, 40, np.float64(0.2))  1.0  0.022917  7.941319e+07  78406083.0
28   (3, 50, np.float64(0.1))  1.0  0.020833  7.550767e+07  76077979.0
29   (3, 50, np.float64(0.2))  1.0  0.020833  7.514781e+07  74897500.0
2    (1, 30, np.float64(0.1))  1.0  0.012500  8.104327e+07  80234062.5
27   (3, 40, np.float64(0.2))  1.0  0.012500  7.529038e+07  75156396.0
3    (1, 30, np.float64(0.2))  1.0  0.012500  8.078720e+07  80918583.0
26   (3, 40, np.float64(0.1))  1.0  0.012500  7.660838e+07  76845125.5
24   (3, 30, np.float64(0.1))  1.0  0.008333  7.640493e+07  76730708.5
25   (3, 30, np.float64(0.2))  1.0  0.008333  7.597180e+07  76377812.5
0    (1, 20, np.float64(0.1))  1.0  0.006250  8.240381e+07  82393271.0
1    (1, 20, np.float64(0.2))  1.0  0.006250  8.127278e+07  84024958.5
23   (3, 20, np.float64(0.2))  1.0  0.002083  7.750082e+07  76422229.0
22   (3, 20, np.float64(0.1))  1.0  0.002083  7.773973e+07  77878667.0

In [ ]:
## Look at the binary results for all the hyperparameter tests, and sort by accuracy.
binary_csv = pd.read_csv(output_file_dict.get("bigpicture0"))
binary_csv.sort_values("1", ascending= False)

                        Unnamed: 0    0         1             2           3
16  (1, 310, np.float64(0.2), 180)  0.0  0.168750  6.882865e+07  66129437.5
21  (1, 320, np.float64(0.1), 180)  0.0  0.168750  6.921094e+07  66584250.0
26  (1, 320, np.float64(0.2), 180)  0.0  0.168750  6.928718e+07  67235729.0
11  (1, 310, np.float64(0.1), 180)  0.0  0.168750  6.852656e+07  65545583.5
1   (1, 300, np.float64(0.1), 180)  0.0  0.166667  6.949607e+07  66832333.5
6   (1, 300, np.float64(0.2), 180)  0.0  0.166667  6.885873e+07  65846250.0
15  (1, 310, np.float64(0.2), 170)  0.0  0.162500  7.022022e+07  69536896.0
25  (1, 320, np.float64(0.2), 170)  0.0  0.162500  7.094757e+07  69678937.0
10  (1, 310, np.float64(0.1), 170)  0.0  0.162500  7.089008e+07  70750312.5
0   (1, 300, np.float64(0.1), 170)  0.0  0.162500  7.201109e+07  67946896.0
20  (1, 320, np.float64(0.1), 170)  0.0  0.162500  7.067214e+07  70466917.0
5   (1, 300, np.float64(0.2), 170)  0.0  0.162500  7.051727e+07  69863312.5
40  (3, 310, np.float64(0.1), 170)  0.0  0.160417  5.766995e+07  55763312.5
45  (3, 310, np.float64(0.2), 170)  0.0  0.160417  5.687371e+07  55843437.5
50  (3, 320, np.float64(0.1), 170)  0.0  0.160417  5.681205e+07  56238750.0
55  (3, 320, np.float64(0.2), 170)  0.0  0.160417  5.103185e+07  48607333.0
35  (3, 300, np.float64(0.2), 170)  0.0  0.156250  5.640210e+07  54244895.5
30  (3, 300, np.float64(0.1), 170)  0.0  0.156250  5.638929e+07  55854437.5
46  (3, 310, np.float64(0.2), 180)  0.0  0.127083  5.533620e+07  53724250.0
41  (3, 310, np.float64(0.1), 180)  0.0  0.127083  5.620205e+07  53329771.0
51  (3, 320, np.float64(0.1), 180)  0.0  0.127083  5.498576e+07  53609083.5
56  (3, 320, np.float64(0.2), 180)  0.0  0.127083  4.939567e+07  47184979.0
36  (3, 300, np.float64(0.2), 180)  0.0  0.127083  5.564120e+07  52896791.5
31  (3, 300, np.float64(0.1), 180)  0.0  0.127083  5.523811e+07  52727833.5
2   (1, 300, np.float64(0.1), 190)  0.0  0.100000  6.111354e+07  57932999.5
17  (1, 310, np.float64(0.2), 190)  0.0  0.100000  6.104432e+07  57395937.5
22  (1, 320, np.float64(0.1), 190)  0.0  0.100000  6.048249e+07  56646604.0
7   (1, 300, np.float64(0.2), 190)  0.0  0.100000  6.074718e+07  58322333.0
12  (1, 310, np.float64(0.1), 190)  0.0  0.100000  6.092468e+07  56623187.5
27  (1, 320, np.float64(0.2), 190)  0.0  0.100000  6.132883e+07  56586395.5
52  (3, 320, np.float64(0.1), 190)  0.0  0.047917  4.985515e+07  48483354.0
37  (3, 300, np.float64(0.2), 190)  0.0  0.047917  4.938832e+07  47452000.0
42  (3, 310, np.float64(0.1), 190)  0.0  0.047917  5.024664e+07  48320021.0
32  (3, 300, np.float64(0.1), 190)  0.0  0.047917  5.086230e+07  49924500.5
57  (3, 320, np.float64(0.2), 190)  0.0  0.047917  4.463992e+07  43251708.5
47  (3, 310, np.float64(0.2), 190)  0.0  0.047917  5.103864e+07  48987520.5
3   (1, 300, np.float64(0.1), 200)  0.0  0.025000  5.004864e+07  45674813.0
8   (1, 300, np.float64(0.2), 200)  0.0  0.025000  4.985592e+07  45426229.5
28  (1, 320, np.float64(0.2), 200)  0.0  0.025000  5.094964e+07  45536708.5
13  (1, 310, np.float64(0.1), 200)  0.0  0.025000  5.021763e+07  45829750.0
23  (1, 320, np.float64(0.1), 200)  0.0  0.025000  4.919234e+07  43766000.0
18  (1, 310, np.float64(0.2), 200)  0.0  0.025000  4.931076e+07  45823708.0
43  (3, 310, np.float64(0.1), 200)  0.0  0.016667  4.460593e+07  43123562.5
33  (3, 300, np.float64(0.1), 200)  0.0  0.016667  4.299059e+07  40507791.5
53  (3, 320, np.float64(0.1), 200)  0.0  0.016667  4.177437e+07  40268833.0
38  (3, 300, np.float64(0.2), 200)  0.0  0.016667  4.344827e+07  42444645.5
58  (3, 320, np.float64(0.2), 200)  0.0  0.016667  3.941163e+07  37166521.0
48  (3, 310, np.float64(0.2), 200)  0.0  0.016667  4.312126e+07  41480250.0
54  (3, 320, np.float64(0.1), 210)  0.0  0.008333  3.690543e+07  36657229.5
39  (3, 300, np.float64(0.2), 210)  0.0  0.008333  3.810511e+07  37558187.5
49  (3, 310, np.float64(0.2), 210)  0.0  0.008333  3.792142e+07  37129000.0
4   (1, 300, np.float64(0.1), 210)  0.0  0.008333  3.898549e+07  36520770.5
44  (3, 310, np.float64(0.1), 210)  0.0  0.008333  3.758994e+07  37548729.0
19  (1, 310, np.float64(0.2), 210)  0.0  0.008333  3.755376e+07  34573499.5
34  (3, 300, np.float64(0.1), 210)  0.0  0.008333  3.818008e+07  37300541.5
9   (1, 300, np.float64(0.2), 210)  0.0  0.008333  3.875656e+07  35935562.5
29  (1, 320, np.float64(0.2), 210)  0.0  0.008333  3.817663e+07  36181416.5
24  (1, 320, np.float64(0.1), 210)  0.0  0.008333  3.872978e+07  36734417.0
14  (1, 310, np.float64(0.1), 210)  0.0  0.008333  3.812404e+07  35359542.0
59  (3, 320, np.float64(0.2), 210)  0.0  0.008333  3.408851e+07  33295500.0