In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as stats
import puck.experiments.best_thresholding.binary_otsu as bo

In [2]:
output_file_dict = bo.main(
    adjustment_on = True,
    cli_printout = False
    )

<class 'dict'>

100%|██████████| 60/60 [00:58<00:00,  1.03it/s]

<class 'dict'>

100%|██████████| 44/44 [00:59<00:00,  1.36s/it]

In [3]:
output_file_dict

{'bigpicture0': '../output/experimental_results/binary_otsu_big_picture/binary0_results.csv',
 'bigpicture1': '../output/experimental_results/binary_otsu_big_picture/otsu0_results.csv',
 'results0': '../output/experimental_results/binary_otsu_pipeline_results/0',
 'results1': '../output/experimental_results/binary_otsu_pipeline_results/1',
 'output_timing': '../output/timing_results/timingResults_binary_otsu_20260330_111630.txt'}

In [4]:
otsu_csv = pd.read_csv(output_file_dict.get("bigpicture1"))
otsu_csv

                   Unnamed: 0    0         1             2           3
0    (1, 20, np.float64(0.1))  1.0  0.012500  8.051859e+07  79398125.0
1    (1, 20, np.float64(0.2))  1.0  0.012500  7.956973e+07  77747917.0
2    (1, 30, np.float64(0.1))  1.0  0.020833  8.057322e+07  78121396.0
3    (1, 30, np.float64(0.2))  1.0  0.020833  7.943693e+07  77024958.5
4    (1, 40, np.float64(0.1))  1.0  0.029167  7.927623e+07  78757937.5
5    (1, 40, np.float64(0.2))  1.0  0.029167  7.941544e+07  78727541.5
6    (1, 50, np.float64(0.1))  1.0  0.037500  7.989605e+07  78876437.5
7    (1, 50, np.float64(0.2))  1.0  0.037500  7.872083e+07  79101375.5
8    (1, 60, np.float64(0.1))  1.0  0.039583  7.835457e+07  76776395.5
9    (1, 60, np.float64(0.2))  1.0  0.039583  7.846205e+07  77187521.0
10   (1, 70, np.float64(0.1))  1.0  0.039583  7.877868e+07  76246083.5
11   (1, 70, np.float64(0.2))  1.0  0.039583  7.846273e+07  76202833.5
12   (1, 80, np.float64(0.1))  1.0  0.043750  7.822290e+07  76599458.0
13   (1, 80, np.float64(0.2))  1.0  0.043750  7.808638e+07  76355708.0
14   (1, 90, np.float64(0.1))  1.0  0.043750  7.773932e+07  75267479.5
15   (1, 90, np.float64(0.2))  1.0  0.043750  7.806577e+07  74505563.0
16  (1, 100, np.float64(0.1))  1.0  0.045833  7.857082e+07  74882687.5
17  (1, 100, np.float64(0.2))  1.0  0.045833  7.731096e+07  73943959.0
18  (1, 110, np.float64(0.1))  1.0  0.047917  7.834568e+07  75441229.0
19  (1, 110, np.float64(0.2))  1.0  0.047917  7.684643e+07  72754916.5
20  (1, 120, np.float64(0.1))  1.0  0.050000  8.008390e+07  78582625.0
21  (1, 120, np.float64(0.2))  1.0  0.050000  7.841190e+07  76381396.0
22   (3, 20, np.float64(0.1))  1.0  0.004167  7.814466e+07  76851645.5
23   (3, 20, np.float64(0.2))  1.0  0.004167  7.783009e+07  74445229.0
24   (3, 30, np.float64(0.1))  1.0  0.014583  7.773773e+07  76481438.0
25   (3, 30, np.float64(0.2))  1.0  0.014583  7.707653e+07  74474854.0
26   (3, 40, np.float64(0.1))  1.0  0.018750  7.721767e+07  75101520.5
27   (3, 40, np.float64(0.2))  1.0  0.018750  7.638324e+07  74426229.0
28   (3, 50, np.float64(0.1))  1.0  0.018750  7.782594e+07  75750625.0
29   (3, 50, np.float64(0.2))  1.0  0.018750  7.672911e+07  73525583.5
30   (3, 60, np.float64(0.1))  1.0  0.020833  7.767615e+07  74247896.0
31   (3, 60, np.float64(0.2))  1.0  0.020833  7.667190e+07  74187250.0
32   (3, 70, np.float64(0.1))  1.0  0.029167  7.772158e+07  74469833.0
33   (3, 70, np.float64(0.2))  1.0  0.029167  7.630637e+07  75213000.0
34   (3, 80, np.float64(0.1))  1.0  0.033333  7.767179e+07  74282979.0
35   (3, 80, np.float64(0.2))  1.0  0.033333  7.633929e+07  74582041.5
36   (3, 90, np.float64(0.1))  1.0  0.033333  7.705971e+07  75215666.5
37   (3, 90, np.float64(0.2))  1.0  0.033333  7.726460e+07  74152125.0
38  (3, 100, np.float64(0.1))  1.0  0.037500  7.651594e+07  73301125.0
39  (3, 100, np.float64(0.2))  1.0  0.037500  7.648790e+07  74951792.0
40  (3, 110, np.float64(0.1))  1.0  0.041667  6.273891e+07  58990750.0
41  (3, 110, np.float64(0.2))  1.0  0.041667  6.229058e+07  61105770.5
42  (3, 120, np.float64(0.1))  1.0  0.043750  6.194301e+07  59935021.0
43  (3, 120, np.float64(0.2))  1.0  0.043750  6.217107e+07  59808729.0

In [5]:
otsu_csv.sort_values("1", ascending= False)

                   Unnamed: 0    0         1             2           3
20  (1, 120, np.float64(0.1))  1.0  0.050000  8.008390e+07  78582625.0
21  (1, 120, np.float64(0.2))  1.0  0.050000  7.841190e+07  76381396.0
19  (1, 110, np.float64(0.2))  1.0  0.047917  7.684643e+07  72754916.5
18  (1, 110, np.float64(0.1))  1.0  0.047917  7.834568e+07  75441229.0
17  (1, 100, np.float64(0.2))  1.0  0.045833  7.731096e+07  73943959.0
16  (1, 100, np.float64(0.1))  1.0  0.045833  7.857082e+07  74882687.5
12   (1, 80, np.float64(0.1))  1.0  0.043750  7.822290e+07  76599458.0
42  (3, 120, np.float64(0.1))  1.0  0.043750  6.194301e+07  59935021.0
15   (1, 90, np.float64(0.2))  1.0  0.043750  7.806577e+07  74505563.0
14   (1, 90, np.float64(0.1))  1.0  0.043750  7.773932e+07  75267479.5
13   (1, 80, np.float64(0.2))  1.0  0.043750  7.808638e+07  76355708.0
43  (3, 120, np.float64(0.2))  1.0  0.043750  6.217107e+07  59808729.0
40  (3, 110, np.float64(0.1))  1.0  0.041667  6.273891e+07  58990750.0
41  (3, 110, np.float64(0.2))  1.0  0.041667  6.229058e+07  61105770.5
11   (1, 70, np.float64(0.2))  1.0  0.039583  7.846273e+07  76202833.5
9    (1, 60, np.float64(0.2))  1.0  0.039583  7.846205e+07  77187521.0
8    (1, 60, np.float64(0.1))  1.0  0.039583  7.835457e+07  76776395.5
10   (1, 70, np.float64(0.1))  1.0  0.039583  7.877868e+07  76246083.5
38  (3, 100, np.float64(0.1))  1.0  0.037500  7.651594e+07  73301125.0
39  (3, 100, np.float64(0.2))  1.0  0.037500  7.648790e+07  74951792.0
7    (1, 50, np.float64(0.2))  1.0  0.037500  7.872083e+07  79101375.5
6    (1, 50, np.float64(0.1))  1.0  0.037500  7.989605e+07  78876437.5
37   (3, 90, np.float64(0.2))  1.0  0.033333  7.726460e+07  74152125.0
36   (3, 90, np.float64(0.1))  1.0  0.033333  7.705971e+07  75215666.5
35   (3, 80, np.float64(0.2))  1.0  0.033333  7.633929e+07  74582041.5
34   (3, 80, np.float64(0.1))  1.0  0.033333  7.767179e+07  74282979.0
4    (1, 40, np.float64(0.1))  1.0  0.029167  7.927623e+07  78757937.5
5    (1, 40, np.float64(0.2))  1.0  0.029167  7.941544e+07  78727541.5
33   (3, 70, np.float64(0.2))  1.0  0.029167  7.630637e+07  75213000.0
32   (3, 70, np.float64(0.1))  1.0  0.029167  7.772158e+07  74469833.0
31   (3, 60, np.float64(0.2))  1.0  0.020833  7.667190e+07  74187250.0
30   (3, 60, np.float64(0.1))  1.0  0.020833  7.767615e+07  74247896.0
3    (1, 30, np.float64(0.2))  1.0  0.020833  7.943693e+07  77024958.5
2    (1, 30, np.float64(0.1))  1.0  0.020833  8.057322e+07  78121396.0
29   (3, 50, np.float64(0.2))  1.0  0.018750  7.672911e+07  73525583.5
28   (3, 50, np.float64(0.1))  1.0  0.018750  7.782594e+07  75750625.0
27   (3, 40, np.float64(0.2))  1.0  0.018750  7.638324e+07  74426229.0
26   (3, 40, np.float64(0.1))  1.0  0.018750  7.721767e+07  75101520.5
25   (3, 30, np.float64(0.2))  1.0  0.014583  7.707653e+07  74474854.0
24   (3, 30, np.float64(0.1))  1.0  0.014583  7.773773e+07  76481438.0
0    (1, 20, np.float64(0.1))  1.0  0.012500  8.051859e+07  79398125.0
1    (1, 20, np.float64(0.2))  1.0  0.012500  7.956973e+07  77747917.0
23   (3, 20, np.float64(0.2))  1.0  0.004167  7.783009e+07  74445229.0
22   (3, 20, np.float64(0.1))  1.0  0.004167  7.814466e+07  76851645.5

In [6]:
binary_csv = pd.read_csv(output_file_dict.get("bigpicture0"))
binary_csv.sort_values("1", ascending= False)

                        Unnamed: 0    0         1             2           3
16  (1, 310, np.float64(0.2), 180)  0.0  0.168750  6.782844e+07  64376937.0
21  (1, 320, np.float64(0.1), 180)  0.0  0.168750  6.827132e+07  66608854.0
26  (1, 320, np.float64(0.2), 180)  0.0  0.168750  6.862497e+07  66633854.0
11  (1, 310, np.float64(0.1), 180)  0.0  0.168750  6.737553e+07  65248333.5
1   (1, 300, np.float64(0.1), 180)  0.0  0.166667  6.897053e+07  65623395.5
6   (1, 300, np.float64(0.2), 180)  0.0  0.166667  6.848183e+07  64686000.5
15  (1, 310, np.float64(0.2), 170)  0.0  0.162500  7.003085e+07  68467604.5
25  (1, 320, np.float64(0.2), 170)  0.0  0.162500  6.980604e+07  70127896.0
10  (1, 310, np.float64(0.1), 170)  0.0  0.162500  6.958031e+07  69244479.0
0   (1, 300, np.float64(0.1), 170)  0.0  0.162500  7.109294e+07  69733000.0
20  (1, 320, np.float64(0.1), 170)  0.0  0.162500  7.068149e+07  70647146.0
5   (1, 300, np.float64(0.2), 170)  0.0  0.162500  7.097166e+07  68557458.5
40  (3, 310, np.float64(0.1), 170)  0.0  0.160417  5.671875e+07  55581875.0
45  (3, 310, np.float64(0.2), 170)  0.0  0.160417  5.588614e+07  54659062.0
50  (3, 320, np.float64(0.1), 170)  0.0  0.160417  5.725797e+07  57911062.5
55  (3, 320, np.float64(0.2), 170)  0.0  0.160417  5.385641e+07  52300875.5
35  (3, 300, np.float64(0.2), 170)  0.0  0.156250  5.581122e+07  53777333.0
30  (3, 300, np.float64(0.1), 170)  0.0  0.156250  5.576878e+07  53951374.5
46  (3, 310, np.float64(0.2), 180)  0.0  0.127083  5.491686e+07  52062083.5
41  (3, 310, np.float64(0.1), 180)  0.0  0.127083  5.532905e+07  52219604.0
51  (3, 320, np.float64(0.1), 180)  0.0  0.127083  5.583899e+07  54099542.0
56  (3, 320, np.float64(0.2), 180)  0.0  0.127083  5.279092e+07  50147312.0
36  (3, 300, np.float64(0.2), 180)  0.0  0.127083  5.476448e+07  53597062.5
31  (3, 300, np.float64(0.1), 180)  0.0  0.127083  5.430987e+07  51489000.0
2   (1, 300, np.float64(0.1), 190)  0.0  0.100000  6.041469e+07  55702167.0
17  (1, 310, np.float64(0.2), 190)  0.0  0.100000  6.000926e+07  55927042.0
22  (1, 320, np.float64(0.1), 190)  0.0  0.100000  6.072042e+07  56619500.5
7   (1, 300, np.float64(0.2), 190)  0.0  0.100000  5.968012e+07  55661021.0
12  (1, 310, np.float64(0.1), 190)  0.0  0.100000  5.982105e+07  56940166.5
27  (1, 320, np.float64(0.2), 190)  0.0  0.100000  6.034703e+07  56579875.0
52  (3, 320, np.float64(0.1), 190)  0.0  0.047917  5.109833e+07  49599187.5
37  (3, 300, np.float64(0.2), 190)  0.0  0.047917  5.027469e+07  48961917.0
42  (3, 310, np.float64(0.1), 190)  0.0  0.047917  5.078469e+07  48818020.5
32  (3, 300, np.float64(0.1), 190)  0.0  0.047917  4.957500e+07  48450209.0
57  (3, 320, np.float64(0.2), 190)  0.0  0.047917  4.676404e+07  45005521.0
47  (3, 310, np.float64(0.2), 190)  0.0  0.047917  4.929930e+07  47283271.0
3   (1, 300, np.float64(0.1), 200)  0.0  0.025000  5.022974e+07  46883479.0
8   (1, 300, np.float64(0.2), 200)  0.0  0.025000  4.991408e+07  46186542.0
28  (1, 320, np.float64(0.2), 200)  0.0  0.025000  4.951027e+07  46765271.0
13  (1, 310, np.float64(0.1), 200)  0.0  0.025000  4.948743e+07  45671520.5
23  (1, 320, np.float64(0.1), 200)  0.0  0.025000  4.978462e+07  47415229.0
18  (1, 310, np.float64(0.2), 200)  0.0  0.025000  4.895661e+07  45550792.0
43  (3, 310, np.float64(0.1), 200)  0.0  0.016667  4.275066e+07  41897791.5
33  (3, 300, np.float64(0.1), 200)  0.0  0.016667  4.221360e+07  40602208.5
53  (3, 320, np.float64(0.1), 200)  0.0  0.016667  4.299386e+07  41509979.5
38  (3, 300, np.float64(0.2), 200)  0.0  0.016667  4.326523e+07  41112750.0
58  (3, 320, np.float64(0.2), 200)  0.0  0.016667  4.038561e+07  38771000.0
48  (3, 310, np.float64(0.2), 200)  0.0  0.016667  4.291632e+07  41120666.5
54  (3, 320, np.float64(0.1), 210)  0.0  0.008333  3.772025e+07  38011270.5
39  (3, 300, np.float64(0.2), 210)  0.0  0.008333  3.799226e+07  37526437.5
49  (3, 310, np.float64(0.2), 210)  0.0  0.008333  3.687541e+07  36229604.0
4   (1, 300, np.float64(0.1), 210)  0.0  0.008333  4.051288e+07  38308896.0
44  (3, 310, np.float64(0.1), 210)  0.0  0.008333  3.744936e+07  37489208.0
19  (1, 310, np.float64(0.2), 210)  0.0  0.008333  3.797213e+07  34225354.0
34  (3, 300, np.float64(0.1), 210)  0.0  0.008333  3.740346e+07  36483042.0
9   (1, 300, np.float64(0.2), 210)  0.0  0.008333  3.929312e+07  37428437.5
29  (1, 320, np.float64(0.2), 210)  0.0  0.008333  3.860730e+07  37463000.5
24  (1, 320, np.float64(0.1), 210)  0.0  0.008333  3.953309e+07  37898875.0
14  (1, 310, np.float64(0.1), 210)  0.0  0.008333  3.825264e+07  35685625.0
59  (3, 320, np.float64(0.2), 210)  0.0  0.008333  3.515025e+07  35292646.0